name: Update README with new entry
permissions:
  contents: write
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables for testing
        run: |
          echo "name_env=TestName" >> $GITHUB_ENV
          echo "date_env=16-07-2024" >> $GITHUB_ENV

      - name: Extract environment variables and update README
        run: |
          # Read the environment variables
          name_env="${{ env.name_env }}"
          date_env="${{ env.date_env }}"

          NEW_ROW="| ${NAME} | ${DATE} |"
          echo "NEW_ROW=$NEW_ROW" 

          # Read the README into a variable
          README=$(cat README.md)

          # Find the position of the table end
          TABLE_END_POS=$(echo "$README" | grep -n -o -e "$TABLE_END" | cut -d ':' -f 1)

          # Insert the new row before the table end
          README=$(echo "$README" | sed "${TABLE_END_POS}i${NEW_ROW}")

          # Overwrite the README file
          echo "$README" > README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with new entry"
          git push
