name: first-github-rest-api
on:
  workflow_dispatch
jobs:
  github-api:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: run bash script
        run: |
          echo hello
      - name: branch name
        run: 
          echo "${{ github.ref }} branch"

    
