name: first-github-rest-api
on:
  workflow_dispatch
jobs:
  github-api:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: clone repo
        uses: action/checkout@v4
      - name: run bash script
        run: |
          bash bash.sh

    
