name: Update README with directory tree
permissions:
  contents: write 

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install tree
      run: sudo apt-get install -y tree

    - name: Generate directory tree
      run: tree -L 2 > tree.txt

    - name: Update README.md
      run: |
        sed -i '/<!-- BEGIN TREE -->/,/<!-- END TREE -->/c\
        <!-- BEGIN TREE -->\n\
        ```\n\
        $(cat tree.txt)\n\
        ```\n\
        <!-- END TREE -->' README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update README with latest directory tree"
        git push
     
 
        
