name: Update README with directory tree

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allows the workflow to push changes to the repository

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install tree
      run: sudo apt-get install -y tree

    - name: Generate directory tree
      run: tree -L 2 > tree.txt

    - name: Update README.md
      run: |
        TREE_CONTENT=$(cat tree.txt)
        sed -i '/<!-- BEGIN TREE -->/,/<!-- END TREE -->/c\
        <!-- BEGIN TREE -->\
        ```\
        '"$TREE_CONTENT"'\
        ```\
        <!-- END TREE -->' README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update README with latest directory tree"
        git push
      
